[tool.poetry]
name = "minigrim0"
version = "0.1.0"
description = "Minigrim0's website"
authors = ["Minigrim0 <grimauflorent@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
flask-sqlalchemy = "^3.0.5"
flask-login = "^0.6.2"
python-dotenv = "^1.0.0"
flask-markdown = "^0.3"
redis = "^4.6.0"
flask-sitemap = "^0.4.0"
django = "^5.0"
markdown = "^3.5.1"

[tool.poetry.group.dev.dependencies]
isort = "^5.12.0"
pylint = "^2.17.4"
black = "^23.7.0"


[tool.poetry.group.prod.dependencies]
gunicorn = "^21.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
