version: '3'

services:
  # The main flask webserver
  web:
    build:
      dockerfile: docker/web.dockerfile
      context: ..
    expose:
      - 8000
    env_file:
      - ./.env.prod
    volumes:
      - static_volume:/static
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.githubcron.schedule: "@every 1h"
      ofelia.job-exec.githubcron.command: "/bin/minigrim0"
    restart: unless-stopped

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - static_volume:/flask_static
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.minigrim0-web-web-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.minigrim0-web-insecure.entrypoints=web"
      - "traefik.http.routers.minigrim0-web-insecure.middlewares=minigrim0-web-redirect"
      - "traefik.http.routers.minigrim0-web-insecure.rule=Host(`minigrim0.xyz`)"
      - "traefik.http.routers.minigrim0-web-insecure.service=minigrim0-web"
      - "traefik.http.routers.minigrim0-web-local-insecure.entrypoints=web"
      - "traefik.http.routers.minigrim0-web-local-insecure.middlewares=minigrim0-web-redirect"
      - "traefik.http.routers.minigrim0-web-local-insecure.rule=Host(`web.trappe.local`)"
      - "traefik.http.routers.minigrim0-web-local-insecure.service=minigrim0-web"
      - "traefik.http.routers.minigrim0-web-local.entrypoints=websecure"
      - "traefik.http.routers.minigrim0-web-local.rule=Host(`web.trappe.local`)"
      - "traefik.http.routers.minigrim0-web-local.service=minigrim0-web"
      - "traefik.http.routers.minigrim0-web-local.tls=true"
      - "traefik.http.routers.minigrim0-web.entrypoints=websecure"
      - "traefik.http.routers.minigrim0-web.rule=Host(`minigrim0.xyz`)"
      - "traefik.http.routers.minigrim0-web.service=minigrim0-web"
      - "traefik.http.routers.minigrim0-web.tls.certresolver=myresolver"
      - "traefik.http.services.minigrim0-web.loadbalancer.server.port=8000"
    depends_on:
      - web
    restart: unless-stopped

  postgres:
    image: postgres:12.1-alpine
    env_file:
      - ./.env.prod.db
    volumes:
      - ./data/postgres/:/var/lib/postgresql/data/
    restart: unless-stopped

volumes:
  static_volume:
