services:
  web:
    build:
      dockerfile: docker/web.dockerfile
      context: ..
    expose:
      - 8000
    env_file:
      - ./.env.prod
    volumes:
      - static_volume:/static
    depends_on:
      - redis
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.githubcron.schedule: "@every 1h"
      ofelia.job-exec.githubcron.command: "/bin/minigrim0"
    restart: unless-stopped
    networks:
      - private

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - static_volume:/static
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.minigrim0-web-insecure.entrypoints=http"
      - "traefik.http.routers.minigrim0-web-insecure.rule=Host(`minigrim0.xyz`)"
      - "traefik.http.middlewares.minigrim0-web-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.minigrim0-web-insecure.middlewares=minigrim0-web-redirect"
      - "traefik.http.routers.minigrim0-web.entrypoints=https"
      - "traefik.http.routers.minigrim0-web.rule=Host(`minigrim0.xyz`)"
      - "traefik.http.routers.minigrim0-web.tls=true"
      - "traefik.http.routers.minigrim0-web.tls.certresolver=http"
      - "traefik.http.routers.minigrim0-web.service=nginx-minigrim0-web"
      - "traefik.docker.network=traefik-proxy"
    depends_on:
      - web
    networks:
      - traefik-proxy
      - private
    restart: unless-stopped

  postgres:
    image: postgres:12.1-alpine
    env_file:
      - ./.env.prod.db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: unless-stopped
    networks:
      - private

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
    expose:
      - 6379
    restart: unless-stopped
    networks:
      - private


volumes:
  static_volume:
  postgres_data:
  redis_data:

networks:
  traefik-proxy:
    external: true
  private:
    driver: overlay
    attachable: true