version: '3.8'

services:
  web:
    build:
      context: ..
      dockerfile: docker/web.dev.dockerfile
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - ..:/usr/src/app/
    ports:
      - 8080:8080
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data
    environment:
      - POSTGRES_USER=minidebug
      - POSTGRES_PASSWORD=minidebug
      - POSTGRES_DB=minidebug_db

volumes:
  postgres_data:
