[package]
name = "minigrim0"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper = "0.14.27"
json = "0.12.4"
octocrab = "0.27.0"
tokio = { version = "1", features = ["full"] }
